// this file was generated by 'GenerateConstExprData.cpp'

#include <string>

struct ConstexprRandomUniqueStdStringKeys {
	static constexpr unsigned                              keysLength = 1'024'000;
	static const std::array<std::string_view, keysLength>  keys;
};