// this file was generated by 'GenerateConstExprData.cpp'

#include <EASTL/string.h>

struct ConstexprRandomUniqueEastlStringKeys {
	static constexpr unsigned                                keysLength = 1'024'000;
	static const std::array<eastl::string_view, keysLength>  keys;
};